export interface ColorType {
  BgColor01: string // colorBgColorLightGray colorBgColorDarkBlack
  BgColor02: string // colorBgColorLightWhite colorBgColorDarkGrey
  BgColor03: string // colorBgColorLightLightGrey colorBgColorDarkDarkGray
  BgColorPopup: string
  BgColorInfo: string
  PrimaryColor10: string
  PrimaryColor20: string
  PrimaryColor30: string
  PrimaryColor40: string
  PrimaryColor50: string
  PrimaryColor60: string
  PrimaryColorGreen: string
  TextColorHighlight: string
  TextColor00: string
  TextColor10: string
  TextColor20: string
  TextColor30: string
  TextColor40: string
  TextColor50: string
  TextColor60: string
  TextColor70: string
  TextColor80: string
  TextColor90: string
  TextColor100: string
  BuyColor10: string
  BuyColor20: string
  BuyColor30: string
  BuyColor40: string
  SellColor10: string
  SellColor20: string
  SellColor30: string
  SellColor40: string
  NotificationsBlue01: string
  NotificationsBlue02: string
  NotificationsGreen01: string
  NotificationsGreen02: string
  NotificationsRed01: string
  NotificationsRed02: string
  NotificationsYellow01: string
  NotificationsYellow02: string
  NotificationsPurple01: string
  NotificationsPurple02: string
  TabBgColor: string
  NetWorkSelectBgColor: string
  WithDrawFastOrSlowBgColor: string
  TabHoverColor: string
  BlanceGroupBorderColor: string
  BlanceGroupHoverBgColor: string
  BlanceGroupHoverBorderColor: string
  DarkText00LightPrimay40: string
  DarkPrimay40LightText90: string
  DarkPrimay20LightPrimay30: string
  DarkTextHighlightLightPrimaryGreen: string
  TextColorLightHighlight: string
  DarkText00LightText90: string
  DarkText10LightText90: string
  DarkText10LightWhite: string
  DarkText10LightGrey: string
  DarkText60LightText50: string
  DarkLightText80LightBgGrey: string
  DarkBg02LightText90: string
  DarkText90LightPrimary30: string
  DarkBg03LightBg01: string
  DarkBothLightBg01: string
  DarkBg01LightBg02: string
  DarkBg03LightBg02: string
  DarkBothLightBg02: string
  MobileBgColor: string
  DatePickerInput: string
  TradingTipCloseColor: string
  MarketsMaskColor: string
  DarkBgColor03LightBgColor01: string
  BoxBg01: string
  BoxBg02: string
  BoxBg03: string
  BoxBg04: string
  BoxBorder01: string
  BoxLineBg: string
  BoxBtnBg: string
  BoxBtnBg02: string
  BoxBtnColor: string
  BoxRankBg01: string
  BoxRankBorder01: string
  BoxRankBg02: string
  BoxRankBorder02: string
  BoxRankBg03: string
  BoxRankBorder03: string
  BoxDialogBg: string
  BoxDialogBg02: string
  BoxHistoryRow: string
  TableRow: string
}
